name: Expo CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'soda-tracker/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'soda-tracker/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./soda-tracker

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './soda-tracker/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./soda-tracker/coverage

  e2e-ios:
    needs: test
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./soda-tracker

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './soda-tracker/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Install Detox CLI
      run: npm install -g detox-cli

    - name: Install iOS dependencies
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Build iOS app for testing
      run: npm run e2e:build:ios

    - name: Run E2E tests on iOS
      run: npm run e2e:test:ios

  e2e-android:
    needs: test
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./soda-tracker

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './soda-tracker/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Install Detox CLI
      run: npm install -g detox-cli

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build Android app for testing
      run: npm run e2e:build:android

    - name: Run E2E tests on Android
      run: npm run e2e:test:android

  build-and-deploy:
    needs: [test, e2e-ios, e2e-android]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./soda-tracker

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './soda-tracker/package-lock.json'

    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Install dependencies
      run: npm ci

    - name: Create Firebase config
      run: |
        echo "${{ secrets.FIREBASE_CONFIG }}" > ./config/firebase.ts

    - name: Build Android
      run: |
        expo build:android --non-interactive

    - name: Build iOS
      run: |
        expo build:ios --non-interactive

    - name: Deploy to Expo
      run: |
        expo publish --non-interactive

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Changes in this Release:
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Notify deployment status
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const status = '${{ job.status }}';
          const message = status === 'success' 
            ? '✅ Frontend deployment successful' 
            : '❌ Frontend deployment failed';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });

env:
  CI: true
  NODE_ENV: test
  DETOX_CONFIGURATION: 'ios.sim.debug'