name: Expo CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Install dependencies
      run: yarn install

    - name: Create Firebase config
      run: |
        echo "${{ secrets.FIREBASE_CONFIG }}" > ./config/firebase.ts

    - name: EAS INIT
      run: eas init --non-interactive
      
    - name: Build on EAS
      run: eas build --platform all --non-interactive --no-wait


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Changes in this Release:
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false


env:
  CI: true
  NODE_ENV: test
  DETOX_CONFIGURATION: 'ios.sim.debug'